# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyJSONModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_names', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='NewName',
        ),
    ]
