# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 20:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170210_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myjsonmodel',
            name='json_names',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
